print("Ejercicio 1")
print("Hola Mundo!")
print()

print("Ejercicio 2")
nombre1 = input("ingrese su nombre: ")
print(f"Hola {nombre1}!")
print()

print("Ejercicio 3")
nombre2 = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = input("Ingrese su edad: ")
residencia = input("Ingrese su residencia: ")
print(f"Usted es {nombre2} {apellido} tienes {edad} años y vives en {residencia}")
print()

print("Ejercicio 4")
radio = int(input("Ingrese el radio del círculo: "))
area = radio * radio * 3.14159
perimetro = 2 * 3.14159 * radio
print(f"El área del círculo es de: {area}")
print(f"El perímetro del círculo es de: {perimetro}")
print()

print("Ejercicio 5")
segundos = float(input("Ingrese una cantidad de segundos para mostrar su equivalente a horas: "))
horas = segundos / 3600
print(f"{segundos} segundos equivale a {horas} horas")
print()

print("ejercicio 6")
numero1 = int(input("Ingrese un número: "))
print(f"<<< Tabla del {numero1} >>>")
print(f"{numero1} X 1 = {numero1 * 1}")
print(f"{numero1} X 2 = {numero1 * 2}")
print(f"{numero1} X 3 = {numero1 * 3}")
print(f"{numero1} X 4 = {numero1 * 4}")
print(f"{numero1} X 5 = {numero1 * 5}")
print(f"{numero1} X 6 = {numero1 * 6}")
print(f"{numero1} X 7 = {numero1 * 7}")
print(f"{numero1} X 8 = {numero1 * 8}")
print(f"{numero1} X 9 = {numero1 * 9}")
print(f"{numero1} X 10 = {numero1 * 10}")
print()

print("Ejercicio 7")
numero2 = int(input("Ingrese un número distinto de cero: "))
numero3 = int(input("Ingrese otro número distinto de cero: "))
print(f"{numero2} + {numero3} = {numero2 + numero3}")
print(f"{numero2} - {numero3} = {numero2 - numero3}")
print(f"{numero2} * {numero3} = {numero2 * numero3}")
print(f"{numero2} / {numero3} = {numero2 / numero3}")
print()

print("Ejercicio 8")
altura = float(input("Ingrese su altura en metros: "))
peso = float(input("Ingrese su peso en kilos: "))
indice_masa_corporal = peso / (altura * altura)
print(f"Su indice de masa corporal es de: {indice_masa_corporal}")
print()

print("Ejercicio 9")
celsius = float(input("Ingrese la temperatura en grados Celsius: "))
fahrenheit = celsius * (9/5) + 32
print(f"{celsius}°C equivalen a {fahrenheit}°F")
print()

print("Ejercicio 10")
numero4 = float(input("Ingrese el primer número: "))
numero5 = float(input("Ingrese el segundo número: "))
numero6 = float(input("Ingrese el tercer número: "))
print(f"El promedio de los tres números ingresados es de: {(numero4 + numero5 + numero6) / 5}")
print()